services:

  - type: web

    name: mobile-phone-chatbot

    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:

      - key: GEMINI_API_KEY
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: FIREBASE_PROJECT_ID
        sync: false

      - key: FIREBASE_CLIENT_EMAIL
        sync: false

      - key: FIREBASE_PRIVATE_KEY
        sync: false